apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playback-order
  description: Playback Order
  annotations:
    backstage.io/adr-location: https://github.com/JonathanCabral/pituxinho-backstage/tree/main/examples/docs/ADRs
  tags:
    - java
    - playback
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
