apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher
  description: Searcher
  annotations:
    backstage.io/adr-location: https://github.com/JonathanCabral/pituxinho-backstage/tree/main/examples/docs/ADRs
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
