apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuffle-api
  description: Shuffle API
  annotations:
    backstage.io/adr-location: https://github.com/JonathanCabral/pituxinho-backstage/tree/main/examples/docs/ADRs
  labels:
    goVersion: go1.15.3
    category: music
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
